### ISSUE TITLE
Can't run skill

### ISSUE THREAD

**Issue by psychonetic** [snipsco/snipsskills#25]
Hello,

I am trying to use the snips hue skill.
But if I try to run the snipmanager I get the following error:
`__init__() got an unexpected keyword argument 'locale'`

Any idea?

**Comment by Lomitaii** [comment]
Hi. Have the same issue. Did you manage to solve it?

**Comment by anthonyray** [comment]
Hi ! 

The `locale` argument is expected in the constructor of the `SnipsHue` skill (➡️ https://github.com/snipsco/snips-skill-hue/blob/master/snipshue/snipshue.py#L20). 

You can specify the locale of your skill in two places in the hierarchy of your Snipsfile : 
- At the top level of the Snipsfile
- Pass it as a `params` in your skill definition 

Let's take this Snipsfile as an example : 

```
microphone:
  identifier: respeaker
  params:
    vendor_id: 2886
    product_id: 0007
skills:
  - pip: /home/pi/snips-skill-hue
    name: SnipsHue
    package_name: snipshue
    params:
      locale: en_US
```

Cheers ✌🏾
